import 'package:market_place_mobile/models/prooduct_moodel.dart';

List<Product> productItem = [
  Product(
    name: 'Shiirt',
    imageeUrl: 'assets/images/shirt1.png',
    isFavrite: false,
    itemType: '',
    itemsSold: 2030,
    price: 20,
    rating: 3.0,
    id: '1',
  ),
  Product(
    name: 'Shiirt',
    imageeUrl: 'assets/images/shirt1.png',
    isFavrite: false,
    itemType: '',
    itemsSold: 23560,
    price: 10,
    rating: 4.0,
    id: '1',
  ),
  Product(
    name: 'Shiirt',
    imageeUrl: 'assets/images/shirt2.png',
    isFavrite: false,
    itemType: '',
    itemsSold: 2356,
    price: 15,
    rating: 4.9,
    id: '1',
  ),
  Product(
    name: 'Shiirt',
    imageeUrl: 'assets/images/shirt1.png',
    isFavrite: false,
    itemType: '',
    itemsSold: 1060,
    price: 24,
    rating: 4.0,
    id: '1',
  ),
  Product(
    name: 'Shiirt',
    imageeUrl: 'assets/images/shirt2.png',
    isFavrite: false,
    itemType: '',
    itemsSold: 200,
    price: 13,
    rating: 5.2,
    id: '1',
  ),
  Product(
    name: 'Shiirt',
    imageeUrl: 'assets/images/shirt1.png',
    isFavrite: false,
    itemType: '',
    itemsSold: 2340,
    price: 20,
    rating: 4.2,
    id: '1',
  ),
  Product(
    name: 'Shiirt',
    imageeUrl: 'assets/images/shirt2.png',
    isFavrite: false,
    itemType: '',
    itemsSold: 2506,
    price: 14,
    rating: 3.2,
    id: '1',
  ),
  Product(
    name: 'Shiirt',
    imageeUrl: 'assets/images/shirt1.png',
    isFavrite: false,
    itemType: 'Essn',
    itemsSold: 1996,
    price: 30,
    rating: 3.5,
    id: '1',
  ),
];
